version: '3'
services:
  app:
    build: .
    container_name: task_app
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/interview_task_db
      - SPRING_DATASOURCE_USERNAME=interviewer
      - SPRING_DATASOURCE_PASSWORD=three_tasks
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: postgres_db
    environment:
      - POSTGRES_DB=interview_task_db
      - POSTGRES_USER=interviewer
      - POSTGRES_PASSWORD=three_tasks